clear all; close all;

%%
% CellID, Frame#, X, Y

%% MEAN VELOCITY OVER TIME 
get_voft

%% MEAN SQUARED DISPLACEMENT 10
msd = get_MSD;

%% AUTOCORRELATION FUNCTION OF VELOCITY 10
get_ACF

%% PROBABILITY DENSITY FUNCTION OF DISPLACEMENT 1
get_dR_PDF

%% PROBABILITY DENSITY FUNCTION OF ANGULAR DISPLACEMENT 
get_dtheta_PDF

%% VELOCITY MAGNITUDE POLARIZATION PROFILE 1
get_dR_polarity

%% FITTING OF CELL TRAJECTORIES TO THE APRW MODEL 10
% [P, S, Positioning Error, R Squared. RMSE]
fit_APRW;

%% FITTING OF CELL TRAJECTORIES TO THE PRW MODEL 10
% [P, S, Positioning Error, R Squared. RMSE]
fit_PRW;
%% SIMULATE APRW MODEL // NOT NEEDED!
simxy = sim_APRW;

%% SHOW TRJ'S
